name: Release to NPM

on:
  schedule:
    # schedule uses UTC times
    - cron: '0 5-20/5 * * *'

jobs:
  release_to_npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: 'GIT: Checkout develop branch'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_USER_TOKEN }}
          fetch-depth: '0'

      - name: 'GIT: Fetch master branch'
        run: git fetch origin master:master

      - name: 'GIT: Compare branches'
        id: compare
        run: echo "##[set-output name=commits_ahead;]$(git rev-list --count master..develop)"

      - name: 'GIT: Merge develop into master'
        id: merge
        if: steps.compare.outputs.commits_ahead > 0
        run: |
          git config user.email "litchacha@gmail.com"
          git config user.name "NancyBolstad"
          git checkout master
          git merge --no-edit develop
          git push origin master
          echo "::set-output name=should_publish::true"

      - name: 'NPM: Install'
        if: steps.merge.outputs.should_publish == 'true'
        id: install
        run: 'npm install'

      - name: 'Lerna: Check for changes'
        if: steps.merge.outputs.should_publish == 'true'
        id: changed
        run: npm run lerna -- changed

      - name: 'NPM: Build'
        if: steps.merge.outputs.should_publish == 'true'
        id: build
        run: 'npm run build'

      - name: 'NPM: Configure'
        if: steps.merge.outputs.should_publish == 'true'
        run: |
          echo $'\n//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
          npm whoami
          git update-index --skip-worktree .npmrc
      - name: 'Lerna: Release'
        if: steps.merge.outputs.should_publish == 'true'
        run: 'npm run lerna -- publish --yes'

      - name: 'GIT: Merge master into develop'
        if: steps.merge.outputs.should_publish == 'true'
        run: |
          git update-index --no-skip-worktree .npmrc
          git checkout .npmrc
          git checkout develop
          git pull
          git merge -X theirs --no-edit master
          git push origin develop
          git push --tags